import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  curriculumSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Month 1: AI & ML Foundations',
      collapsible: true,
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'month-1'}],
    },
    {
      type: 'category',
      label: 'Month 2: Deep Learning',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'month-2'}],
    },
    {
      type: 'category',
      label: 'Month 3: NLP & Transformers',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'month-3'}],
    },
    {
      type: 'category',
      label: 'Month 4: Large Language Models',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'month-4'}],
    },
    {
      type: 'category',
      label: 'Month 5: LLM Optimization',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'month-5'}],
    },
    {
      type: 'category',
      label: 'Month 6: Building New Models',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'month-6'}],
    },
  ],
};

export default sidebars;
